#+TITLE: Basic Distributed Algorithms
#+OPTIONS: H:4 toc:nil num:nil
#+LANGUAGE: en
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://gongzhitaao.org/orgcss/org.css"/>


* Exercise 1
Implement in Java the version of *Flood* algorithm for /complete network/.  You
can use the communication mechanisms you prefer.  Test your implementation using
a small network of 3-4 nodes.

*Hint:* Before writing the code, think how you can set up the topology of your
 network and how implement the /spontaneous/ event that starts the protocol.
* Exercise 2
Implement in Java the *Flood* algorithm for /generic topologies/.  You can use
the communication mechanisms you prefer.  Test your implementation using a small
network of 3-4 nodes.

*Hint:* Before writing the code, think how you can set up the topology of your
 network and how implement the /spontaneous/ event that starts the protocol.

* Exercise 3
Implement in Java the *Wake-Up* protocol with multiple initiators. You can use
the communication mechanisms you prefer.  Test your implementation using with a
small network of 3-4 nodes.

*Hint:* Before writing the code, think how you can set up the topology of your
 network and how implement the /spontaneous/ event that starts the protocol.
