#+TITLE: Algorithms for Leader Election
#+OPTIONS: H:4 toc:nil num:nil
#+LANGUAGE: en
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://gongzhitaao.org/orgcss/org.css"/>


* Exercise 1
Implement in Java the *Bully* algorithm for /complete network/.  You
can use the communication mechanisms you prefer.  Test your implementation using
a small network of 3-4 nodes.

*Hint:* Before writing the code, think how you can set up the topology of your
network and how to start the protocol.
* Exercise 2
Implement in Java the *All the way* algorithm for /ring topologies/.  You can use
the communication mechanisms you prefer.  Test your implementation using a small
network of 3-4 nodes.

*Hint:* Before writing the code, think how you can set up the topology of your
 network and how to implement the /spontaneous/ event that starts the protocol.
* Exercise 3
Implement in Java the *AsFar* algorithm for /ring topologies/.  You can use
the communication mechanisms you prefer.  Test your implementation using a small
network of 3-4 nodes.

*Hint:* Before writing the code, think how you can set up the topology of your
network and how to implement the /spontaneous/ event that starts the protocol.
