#+TITLE: Algorithms for Leader Election
#+OPTIONS: H:4 toc:nil num:nil
#+LANGUAGE: en
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://gongzhitaao.org/orgcss/org.css"/>


* Exercise 1
Implement using the simulator JBotSim the *Bully* algorithm for /complete network/.
Before writing the code, think how you can set up the topology of your
network and how to start the protocol.

* Exercise 2
Implement using the simulator JBotSim the *All the way* algorithm for /ring
 topologies/.  Before writing the code, think how you can set up the topology of
 your network and how to implement the /spontaneous/ event that starts the
 protocol.

* Exercise 3
Implement in Java the *AsFar* algorithm for /ring topologies/.
Before writing the code, think how you can set up the topology of your
network and how to implement the /spontaneous/ event that starts the protocol.

* Exercise 4
Implement using JBotSim an algorithm for electing the leader in a network with a tree topology.
Your algorithm should be based on the saturation schema we discussed during the lectures.
Before writing the code, think how you can set up the topology of your
network and how to implement the /spontaneous/ event that starts the protocol.
