#+TITLE: Using MQTT
#+OPTIONS: H:4 toc:nil num:nil
#+LANGUAGE: en
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://gongzhitaao.org/orgcss/org.css"/>


* Exercise 1
Re-implement the remote clock service of [[../ex3/exercises3.org][Exercise 3 of problem set 3]] using MQTT.
The clock should publish a new message with the current time every second using the topic
~"clock1/time"~.
Then, write a client to test your implementation.

* Exercise 2
Extend the clock of the previous exercise as follows.
The clock should publish its status (~ON~ and ~OFF~) using the topic ~"clock1/status~".
Furthermore, once connected to the broker, the clock sets a last will message that informs
subscribers about unwanted disconnectios.

* Exercise 3
Implement a simple chat using MQTT protocol. Think how you can use the communication based on topics to implement
the following:
- the point-to-point communication among users;
- group conversations  among a subset of users;
- the state of a user (if it is online/offline) and its changes.
